# Generated by Django 4.2.16 on 2026-02-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Felonies', 'Felonies'), ('Misdemeanors', 'Misdemeanors'), ('Immigration', 'Immigration'), ('Property Management', 'Property Management'), ('Family Law', 'Family Law'), ('Commercial Law', 'Commercial Law'), ('Labor Law', 'Labor Law'), ('Tax Consulting', 'Tax Consulting'), ('Contracts', 'Contracts'), ('Intellectual Property', 'Intellectual Property')], max_length=60, unique=True)),
                ('price_per_15min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Consultation Categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(choices=[(15, '15 minutes'), (30, '30 minutes'), (60, '1 hour'), (120, '2 hours')])),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='consultations.consultationcategory')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
